# Generated by Django 3.1.3 on 2020-12-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_produckt'),
    ]

    operations = [
        migrations.AddField(
            model_name='produckt',
            name='imageUrl',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
